name: Deploy to Neocities

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Definir ambiente
      id: set-env
      run: |
        if [[ $GITHUB_REF == refs/heads/main ]]; then
          echo "env=production" >> $GITHUB_OUTPUT
        else
          echo "env=staging" >> $GITHUB_OUTPUT
        fi

    - name: Deploy para produção
      if: steps.set-env.outputs.env == 'production'
      uses: neocities/action@v1
      with:
        api-key: ${{ secrets.NEO_API_KEY_PROD }}
        src: "./"

    - name: Deploy para testes
      if: steps.set-env.outputs.env == 'staging'
      uses: neocities/action@v1
      with:
        api-key: ${{ secrets.NEO_API_KEY_STAGING }}
        src: "./"
