name: Deploy to Neocities

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Detect environment
        id: env
        run: |
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            echo "env=production" >> $GITHUB_OUTPUT
          else
            echo "env=staging" >> $GITHUB_OUTPUT
          fi

      - name: Deploy to Neocities (production)
        if: steps.env.outputs.env == 'production'
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEO_API_KEY_PROD }}
          cleanup: false
          dist_dir: './'

      - name: Deploy to Neocities (staging)
        if: steps.env.outputs.env == 'staging'
        uses: bcomnes/deploy-to-neocities@v1
        with:
          api_token: ${{ secrets.NEO_API_KEY_STAGING }}
          cleanup: false
          dist_dir: './'
